import React from 'react'
import { MDBDataTableV5 } from 'mdbreact'
import 'mdbreact/dist/css/mdb.css'
import '@fortawesome/fontawesome-free/css/all.css'



export default function TableProj() {
    

const [datatable, setDatatable] = React.useState({
    columns: [
      {
        label: 'Gouvernorat',
        field: 'name',
        width: 150,
        attributes: {
          'aria-controls': 'DataTable',
          'aria-label': 'Name',
        },
      },
      {
        label: 'Commune',
        field: 'position',
        width: 270,
      },
      {
        label: 'Quartier',
        field: 'office',
        width: 200,
      },
      {
        label: 'Nombre de quartier',
        field: 'Nombre',
        sort: 'asc',
        width: 100,
      },
      {
        label: 'Surface Totale (Hectar)',
        field: 'Surfaces',
        width: 150,
      },
      {
        label: 'Surface Urbanisée (Hectar)',
        field: 'Surface',
        width: 100,
      },
    ],
    rows: [
      {
        name: 'Tiger Nixon',
        position: 'System Architect',
        office: 'Edinburgh',
        Nombre: '61',
        Surfaces: '2011/04/25',
        Surface: '$320',
      },
      {
        name: 'Garrett Winters',
        position: 'Accountant',
        office: 'Tokyo',
        Nombre: '63',
        Surfaces: '2011/07/25',
        Surface: '$170',
      },
      {
        name: 'Ashton Cox',
        position: 'Junior Technical Author',
        office: 'San Francisco',
        Nombre: '66',
        Surfaces: '2009/01/12',
        Surface: '$86',
      },
      {
        name: 'Cedric Kelly',
        position: 'Senior Javascript Developer',
        office: 'Edinburgh',
        Nombre: '22',
        Surfaces: '2012/03/29',
        Surface: '$433',
      },
      {
        name: 'Airi Satou',
        position: 'Accountant',
        office: 'Tokyo',
        Nombre: '33',
        Surfaces: '2008/11/28',
        Surface: '$162',
      },
      {
        name: 'Brielle Williamson',
        position: 'Integration Specialist',
        office: 'New York',
        Nombre: '61',
        Surfaces: '2012/12/02',
        Surface: '$372',
      },
      {
        name: 'Herrod Chandler',
        position: 'Sales Assistant',
        office: 'San Francisco',
        Nombre: '59',
        Surfaces: '2012/08/06',
        Surface: '$137',
      },
      {
        name: 'Rhona Davidson',
        position: 'Integration Specialist',
        office: 'Tokyo',
        Nombre: '55',
        Surfaces: '2010/10/14',
        Surface: '$327',
      },
      {
        name: 'Colleen Hurst',
        position: 'Javascript Developer',
        office: 'San Francisco',
        Nombre: '39',
        Surfaces: '2009/09/15',
        Surface: '$205',
      },
      {
        name: 'Sonya Frost',
        position: 'Software Engineer',
        office: 'Edinburgh',
        Nombre: '23',
        Surfaces: '2008/12/13',
        Surface: '$103',
      },
      {
        name: 'Jena Gaines',
        position: 'Office ManNombrer',
        office: 'London',
        Nombre: '30',
        Surfaces: '2008/12/19',
        Surface: '$90',
      },
      {
        name: 'Quinn Flynn',
        position: 'Support Lead',
        office: 'Edinburgh',
        Nombre: '22',
        Surfaces: '2013/03/03',
        Surface: '$342',
      },
      {
        name: 'Charde Marshall',
        position: 'Regional Director',
        office: 'San Francisco',
        Nombre: '36',
        Surfaces: '2008/10/16',
        Surface: '$470',
      },
      {
        name: 'Haley Kennedy',
        position: 'Senior Marketing Designer',
        office: 'London',
        Nombre: '43',
        Surfaces: '2012/12/18',
        Surface: '$313',
      },
      {
        name: 'Tatyana Fitzpatrick',
        position: 'Regional Director',
        office: 'London',
        Nombre: '19',
        Surfaces: '2010/03/17',
        Surface: '$385',
      },
      {
        name: 'Michael Silva',
        position: 'Marketing Designer',
        office: 'London',
        Nombre: '66',
        Surfaces: '2012/11/27',
        Surface: '$198',
      },
      {
        name: 'Paul Byrd',
        position: 'Chief Financial Officer (CFO)',
        office: 'New York',
        Nombre: '64',
        Surfaces: '2010/06/09',
        Surface: '$725',
      },
      {
        name: 'Gloria Little',
        position: 'Systems Administrator',
        office: 'New York',
        Nombre: '59',
        Surfaces: '2009/04/10',
        Surface: '$237',
      },
      {
        name: 'Bradley Greer',
        position: 'Software Engineer',
        office: 'London',
        Nombre: '41',
        Surfaces: '2012/10/13',
        Surface: '$132',
      },
      {
        name: 'Dai Rios',
        position: 'Personnel Lead',
        office: 'Edinburgh',
        Nombre: '35',
        Surfaces: '2012/09/26',
        Surface: '$217',
      },
      {
        name: 'Jenette Caldwell',
        position: 'Development Lead',
        office: 'New York',
        Nombre: '30',
        Surfaces: '2011/09/03',
        Surface: '$345',
      },
      {
        name: 'Yuri Berry',
        position: 'Chief Marketing Officer (CMO)',
        office: 'New York',
        Nombre: '40',
        Surfaces: '2009/06/25',
        Surface: '$675',
      },
      {
        name: 'Caesar Vance',
        position: 'Pre-Sales Support',
        office: 'New York',
        Nombre: '21',
        Surfaces: '2011/12/12',
        Surface: '$106',
      },
      {
        name: 'Doris Wilder',
        position: 'Sales Assistant',
        office: 'Sidney',
        Nombre: '23',
        Surfaces: '2010/09/20',
        Surface: '$85',
      },
      {
        name: 'Angelica Ramos',
        position: 'Chief Executive Officer (CEO)',
        office: 'London',
        Nombre: '47',
        Surfaces: '2009/10/09',
        Surface: '$1',
      },
      {
        name: 'Gavin Joyce',
        position: 'Developer',
        office: 'Edinburgh',
        Nombre: '42',
        Surfaces: '2010/12/22',
        Surface: '$92',
      },
      {
        name: 'Jennifer Chang',
        position: 'Regional Director',
        office: 'Singapore',
        Nombre: '28',
        Surfaces: '2010/11/14',
        Surface: '$357',
      },
      {
        name: 'Brenden Wagner',
        position: 'Software Engineer',
        office: 'San Francisco',
        Nombre: '28',
        Surfaces: '2011/06/07',
        Surface: '$206',
      },
      {
        name: 'Fiona Green',
        position: 'Chief Operating Officer (COO)',
        office: 'San Francisco',
        Nombre: '48',
        Surfaces: '2010/03/11',
        Surface: '$850',
      },
      {
        name: 'Shou Itou',
        position: 'Regional Marketing',
        office: 'Tokyo',
        Nombre: '20',
        Surfaces: '2011/08/14',
        Surface: '$163',
      },
      {
        name: 'Michelle House',
        position: 'Integration Specialist',
        office: 'Sidney',
        Nombre: '37',
        Surfaces: '2011/06/02',
        Surface: '$95',
      },
      {
        name: 'Suki Burks',
        position: 'Developer',
        office: 'London',
        Nombre: '53',
        Surfaces: '2009/10/22',
        Surface: '$114',
      },
      {
        name: 'Prescott Bartlett',
        position: 'Technical Author',
        office: 'London',
        Nombre: '27',
        Surfaces: '2011/05/07',
        Surface: '$145',
      },
      {
        name: 'Gavin Cortez',
        position: 'Team Leader',
        office: 'San Francisco',
        Nombre: '22',
        Surfaces: '2008/10/26',
        Surface: '$235',
      },
      {
        name: 'Martena Mccray',
        position: 'Post-Sales support',
        office: 'Edinburgh',
        Nombre: '46',
        Surfaces: '2011/03/09',
        Surface: '$324',
      },
      {
        name: 'Unity Butler',
        position: 'Marketing Designer',
        office: 'San Francisco',
        Nombre: '47',
        Surfaces: '2009/12/09',
        Surface: '$85',
      },
      {
        name: 'Howard Hatfield',
        position: 'Office ManNombrer',
        office: 'San Francisco',
        Nombre: '51',
        Surfaces: '2008/12/16',
        Surface: '$164',
      },
      {
        name: 'Hope Fuentes',
        position: 'Secretary',
        office: 'San Francisco',
        Nombre: '41',
        Surfaces: '2010/02/12',
        Surface: '$109',
      },
      {
        name: 'Vivian Harrell',
        position: 'Financial Controller',
        office: 'San Francisco',
        Nombre: '62',
        Surfaces: '2009/02/14',
        Surface: '$452',
      },
      {
        name: 'Timothy Mooney',
        position: 'Office ManNombrer',
        office: 'London',
        Nombre: '37',
        Surfaces: '2008/12/11',
        Surface: '$136',
      },
      {
        name: 'Jackson Bradshaw',
        position: 'Director',
        office: 'New York',
        Nombre: '65',
        Surfaces: '2008/09/26',
        Surface: '$645',
      },
      {
        name: 'Olivia Liang',
        position: 'Support Engineer',
        office: 'Singapore',
        Nombre: '64',
        Surfaces: '2011/02/03',
        Surface: '$234',
      },
      {
        name: 'Bruno Nash',
        position: 'Software Engineer',
        office: 'London',
        Nombre: '38',
        Surfaces: '2011/05/03',
        Surface: '$163',
      },
      {
        name: 'Sakura Yamamoto',
        position: 'Support Engineer',
        office: 'Tokyo',
        Nombre: '37',
        Surfaces: '2009/08/19',
        Surface: '$139',
      },
      {
        name: 'Thor Walton',
        position: 'Developer',
        office: 'New York',
        Nombre: '61',
        Surfaces: '2013/08/11',
        Surface: '$98',
      },
      {
        name: 'Finn Camacho',
        position: 'Support Engineer',
        office: 'San Francisco',
        Nombre: '47',
        Surfaces: '2009/07/07',
        Surface: '$87',
      },
      {
        name: 'Serge Baldwin',
        position: 'Data Coordinator',
        office: 'Singapore',
        Nombre: '64',
        Surfaces: '2012/04/09',
        Surface: '$138',
      },
      {
        name: 'Zenaida Frank',
        position: 'Software Engineer',
        office: 'New York',
        Nombre: '63',
        Surfaces: '2010/01/04',
        Surface: '$125',
      },
      {
        name: 'Zorita Serrano',
        position: 'Software Engineer',
        office: 'San Francisco',
        Nombre: '56',
        Surfaces: '2012/06/01',
        Surface: '$115',
      },
      {
        name: 'Jennifer Acosta',
        position: 'Junior Javascript Developer',
        office: 'Edinburgh',
        Nombre: '43',
        Surfaces: '2013/02/01',
        Surface: '$75',
      },
      {
        name: 'Cara Stevens',
        position: 'Sales Assistant',
        office: 'New York',
        Nombre: '46',
        Surfaces: '2011/12/06',
        Surface: '$145',
      },
      {
        name: 'Hermione Butler',
        position: 'Regional Director',
        office: 'London',
        Nombre: '47',
        Surfaces: '2011/03/21',
        Surface: '$356',
      },
      {
        name: 'Lael Greer',
        position: 'Systems Administrator',
        office: 'London',
        Nombre: '21',
        Surfaces: '2009/02/27',
        Surface: '$103',
      },
      {
        name: 'Jonas Alexander',
        position: 'Developer',
        office: 'San Francisco',
        Nombre: '30',
        Surfaces: '2010/07/14',
        Surface: '$86',
      },
      {
        name: 'Shad Decker',
        position: 'Regional Director',
        office: 'Edinburgh',
        Nombre: '51',
        Surfaces: '2008/11/13',
        Surface: '$183',
      },
      {
        name: 'Michael Bruce',
        position: 'Javascript Developer',
        office: 'Singapore',
        Nombre: '29',
        Surfaces: '2011/06/27',
        Surface: '$183',
      },
      {
        name: 'Donna Snider',
        position: 'Customer Support',
        office: 'New York',
        Nombre: '27',
        Surfaces: '2011/01/25',
        Surface: '$112',
      },
    ],
  });
    return (
        <div >
            
									<MDBDataTableV5 
                  style={{"marginLeft":"3%"}}
                  responsive
										hover 
										entriesOptions={[5, 20, 25]} 
										entries={5} 
										pNombresAmount={4} 
										data={datatable} 
										searchTop 
										searchBottom={false} />
        </div>
    )
}
